{{- if and (include "clickhouseKeeper.deployEnabled" .) .Values.clickhouseKeeper.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouseKeeper.serviceAccountName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.clickhouseKeeper.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.clickhouseKeeper.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
