{{- if not .Values.redis.external.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.redisSecretsName" .}}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
data:
  {{- if .Values.redis.external.enabled }}
    redis_connection_url: {{ .Values.redis.external.connectionUrl | b64enc }}
    redis_tls_enabled: {{ .Values.redis.external.tlsEnabled | b64enc }}
    redis_mode: {{ .Values.redis.external.mode | b64enc }}
    redis_store: {{ .Values.redis.external.store | b64enc }}
  {{- else }}
    redis_connection_url: {{ printf "redis://%s-%s:%v" (include "portkey.fullname" .) .Values.redis.name .Values.redis.containerPort | b64enc }}
    redis_tls_enabled: {{ .Values.redis.external.tlsEnabled | b64enc }}
    redis_mode: {{ .Values.redis.external.mode | b64enc }}
    redis_store: {{ .Values.redis.external.store | b64enc }}
  {{- end}}
{{- end }}
