{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.secretsName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
data:
    jwtPrivateKey: {{ .Values.config.jwtPrivateKey | b64enc | quote }}
  {{- if .Values.config.oauth.enabled }}
    oauthClientId: {{ .Values.config.oauth.oauthClientId | b64enc | quote }}
    oauthIssuerUrl: {{ .Values.config.oauth.oauthIssuerUrl | b64enc | quote }}
    oauthClientSecret: {{ .Values.config.oauth.oauthClientSecret | b64enc | quote }}
    oauthRedirectURI: {{ .Values.config.oauth.oauthRedirectURI | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.smtp.enabled }}
    smtpHost: {{ .Values.config.smtp.smtpHost | b64enc | quote }}
    smtpPort: {{ .Values.config.smtp.smtpPort | b64enc | quote }}
    smtpUser: {{ .Values.config.smtp.smtpUser | b64enc | quote }}
    smtpPassword: {{ .Values.config.smtp.smtpPassword | b64enc | quote }}
    smtpFrom: {{ .Values.config.smtp.smtpFrom | b64enc | quote }}
  {{- end }}
{{- end }}