{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.secretsName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
data:
    jwtPrivateKey: {{ .Values.config.jwtPrivateKey | b64enc | quote }}
  {{- if .Values.config.oauth.enabled }}
    {{- if .Values.config.oauth.oauthType }}
    oauthType: {{ .Values.config.oauth.oauthType | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.oauth.oauthClientId }}
    oauthClientId: {{ .Values.config.oauth.oauthClientId | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.oauth.oauthIssuerUrl }}
    oauthIssuerUrl: {{ .Values.config.oauth.oauthIssuerUrl | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.oauth.oauthClientSecret }}
    oauthClientSecret: {{ .Values.config.oauth.oauthClientSecret | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.oauth.oauthRedirectURI }}
    oauthRedirectURI: {{ .Values.config.oauth.oauthRedirectURI | b64enc | quote }}
    {{- end }}
    {{- if .Values.config.oauth.oauthMetadataXml }}
    oauthMetadataXml: {{ .Values.config.oauth.oauthMetadataXml | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- if .Values.config.smtp.enabled }}
    smtpHost: {{ .Values.config.smtp.smtpHost | b64enc | quote }}
    smtpPort: {{ .Values.config.smtp.smtpPort | b64enc | quote }}
    smtpUser: {{ .Values.config.smtp.smtpUser | b64enc | quote }}
    smtpPassword: {{ .Values.config.smtp.smtpPassword | b64enc | quote }}
    smtpFrom: {{ .Values.config.smtp.smtpFrom | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and (not .Values.mysql.external.enabled) .Values.mysql.external.secretMount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mysql" (include "portkey.fullname" .) }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
data:
  {{ .Values.mysql.external.secretMount.keys.user }}: {{ .Values.mysql.external.user | b64enc | quote }}
  {{ .Values.mysql.external.secretMount.keys.password }}: {{ .Values.mysql.external.password | b64enc | quote }}
  {{ .Values.mysql.external.secretMount.keys.database }}: {{ .Values.mysql.external.database | b64enc | quote }}
  {{ .Values.mysql.external.secretMount.keys.rootPassword }}: {{ .Values.mysql.external.rootPassword | b64enc | quote }}
{{- end }}

{{- if and (not .Values.redis.external.enabled) .Values.redis.external.secretMount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-redis" (include "portkey.fullname" .) }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
data:
  {{ .Values.redis.external.secretMount.keys.connectionUrl }}: {{ .Values.redis.external.connectionUrl | b64enc | quote }}
  {{ .Values.redis.external.secretMount.keys.tlsEnabled }}: {{ .Values.redis.external.tlsEnabled | b64enc | quote }}
  {{ .Values.redis.external.secretMount.keys.mode }}: {{ .Values.redis.external.mode | b64enc | quote }}
  {{ .Values.redis.external.secretMount.keys.store }}: {{ .Values.redis.external.store | b64enc | quote }}
{{- end }}

{{- if and (not .Values.clickhouse.external.enabled) .Values.clickhouse.external.secretMount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-clickhouse" (include "portkey.fullname" .) }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
data:
  {{ .Values.clickhouse.external.secretMount.keys.store }}: {{ .Values.clickhouse.store | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.host }}: {{ .Values.clickhouse.external.host | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.port }}: {{ .Values.clickhouse.external.port | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.nativePort }}: {{ .Values.clickhouse.external.nativePort | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.user }}: {{ .Values.clickhouse.external.user | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.password }}: {{ .Values.clickhouse.external.password | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.database }}: {{ .Values.clickhouse.external.database | b64enc | quote }}
  {{ .Values.clickhouse.external.secretMount.keys.tls }}: {{ .Values.clickhouse.external.tls | toString | b64enc | quote }}
{{- end }}

{{- if and .Values.config.oauth.enabled .Values.config.oauth.secretMount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oauth" (include "portkey.fullname" .) }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
data:
  {{ .Values.config.oauth.secretMount.keys.oauthType }}: {{ .Values.config.oauth.oauthType | b64enc | quote }}
  {{ .Values.config.oauth.secretMount.keys.oauthClientId }}: {{ .Values.config.oauth.oauthClientId | b64enc | quote }}
  {{ .Values.config.oauth.secretMount.keys.oauthIssuerUrl }}: {{ .Values.config.oauth.oauthIssuerUrl | b64enc | quote }}
  {{ .Values.config.oauth.secretMount.keys.oauthClientSecret }}: {{ .Values.config.oauth.oauthClientSecret | b64enc | quote }}
  {{ .Values.config.oauth.secretMount.keys.oauthRedirectURI }}: {{ .Values.config.oauth.oauthRedirectURI | b64enc | quote }}
  {{ .Values.config.oauth.secretMount.keys.oauthMetadataXml }}: {{ .Values.config.oauth.oauthMetadataXml | b64enc | quote }}
{{- end }}

{{- if and .Values.config.smtp.enabled .Values.config.smtp.secretMount.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-smtp" (include "portkey.fullname" .) }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
data:
  {{ .Values.config.smtp.secretMount.keys.host }}: {{ .Values.config.smtp.smtpHost | b64enc | quote }}
  {{ .Values.config.smtp.secretMount.keys.port }}: {{ .Values.config.smtp.smtpPort | b64enc | quote }}
  {{ .Values.config.smtp.secretMount.keys.user }}: {{ .Values.config.smtp.smtpUser | b64enc | quote }}
  {{ .Values.config.smtp.secretMount.keys.password }}: {{ .Values.config.smtp.smtpPassword | b64enc | quote }}
  {{ .Values.config.smtp.secretMount.keys.from }}: {{ .Values.config.smtp.smtpFrom | b64enc | quote }}
{{- end }}