apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.backend.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.backend.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.backend.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.backend.name }}
  template:
    metadata:
      annotations:
      {{- if .Values.backend.deployment.autoRestart }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- with .Values.backend.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.backend.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "portkey.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.backend.name }}
    spec:
      imagePullSecrets: 
      {{- range .Values.imageCredentials }}
      - name: {{ .name }}
      {{- end }}

      securityContext:
        {{- toYaml .Values.backend.deployment.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      containers:
        - name: {{ .Values.backend.name }}
          {{- with .Values.backend.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "portkey.commonEnv" . | nindent 12 }}
            {{- include "logStore.commonEnv" . | nindent 12 }}
            - name: PORT
              value: {{ .Values.backend.containerPort | quote }}
            - name: PRIVATE_DEPLOYMENT
              value: "ON"
            - name: SERVICE_NAME
              value: {{ include "portkey.fullname" . }}-{{ .Values.backend.name }}
            - name: POLYJUICE_FINETUNE_ENDPOINT
              value: http://{{ include "portkey.fullname" . }}-{{ .Values.dataservice.name }}:{{ .Values.dataservice.containerPort }}
            {{- if .Values.gateway.enabled}}  
            - name: GATEWAY_BASE_URL
              value: http://{{ include "portkey.fullname" . }}-{{ .Values.gateway.name }}:{{ .Values.gateway.containerPort }}
            - name: GATEWAY_CACHE_MODE
              value: "SELF"
            {{- else }}
            - name: GATEWAY_BASE_URL
              value: {{ .Values.config.defaultGatewayURL | quote }}
            - name: PRIVATE_CLIENT_AUTH
              value: {{ .Values.config.defaultGatewayClientAuth | quote }}
            {{- end }}
            {{- with .Values.backend.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.commonEnv }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.images.backendImage.repository }}:{{ .Values.images.backendImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.backendImage.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              /app/docker-entrypoint.sh &&
              npx knex migrate:latest --env local &&
              npx knex seed:run --env local &&
              node ch_init.js &&
              pm2-runtime src/server.js
          ports:
            - name: backend
              containerPort: {{ .Values.backend.containerPort }}
              protocol: TCP
          {{- with .Values.backend.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.backend.deployment.securityContext | nindent 12 }}
          {{- with .Values.backend.deployment.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.deployment.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.backend.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}