{{- if not .Values.mysql.external.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.mysql.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.mysql.statefulSet.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.mysql.statefulSet.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "portkey.fullname" . }}-{{ .Values.mysql.name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "portkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.mysql.name }}
  template:
    metadata:
      {{- with .Values.mysql.statefulSet.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.mysql.statefulSet.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "portkey.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.mysql.name }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mysql.statefulSet.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "mysql.serviceAccountName" . }}
      containers:
        - name: {{ .Values.mysql.name }}
          {{- if .Values.mysql.statefulSet.command }}
          command:
            {{- toYaml .Values.mysql.statefulSet.command | nindent 4 }}
          {{- else }}
          args:
            - --sql-mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
          {{- end }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "portkey.mysqlSecretsName" . }}
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "portkey.mysqlSecretsName" . }}
                  key: mysql_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "portkey.mysqlSecretsName" . }}
                  key: mysql_db
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "portkey.mysqlSecretsName" . }}
                  key: mysql_root_password
            {{- if or .Values.mysql.statefulSet.extraEnv .Values.commonEnv  }}
              {{- with .Values.mysql.statefulSet.extraEnv}}
                {{- toYaml . | nindent 12 }}
              {{- end }}
              {{- with .Values.commonEnv}}
                {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
          image: "{{ .Values.images.mysqlImage.repository }}:{{ .Values.images.mysqlImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.mysqlImage.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.containerPort }}
              protocol: TCP
          {{- with .Values.mysql.statefulSet.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mysql.statefulSet.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.mysql.statefulSet.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mysql.statefulSet.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.mysql.statefulSet.securityContext | nindent 12 }}
          {{- if .Values.mysql.statefulSet.persistence.enabled }}
          volumeMounts:
            {{- with .Values.clickhouse.statefulSet.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /var/lib/mysql
              name: data
            {{- with .Values.mysql.statefulSet.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
          {{- with .Values.mysql.statefulSet.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- with .Values.mysql.statefulSet.extraContainerConfig }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.mysql.statefulSet.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.mysql.statefulSet.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.statefulSet.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.statefulSet.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql.statefulSet.volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.mysql.statefulSet.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "portkey.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.mysql.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mysql.statefulSet.persistence.size }}
        {{- if .Values.mysql.statefulSet.persistence.storageClassName }}
        storageClassName: {{ .Values.mysql.statefulSet.persistence.storageClassName }}
        {{- end }}
  {{- end }}
{{- end }}