apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.dataservice.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.dataservice.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.dataservice.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.dataservice.autoscaling.enabled }}
  replicas: {{ .Values.dataservice.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portkey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.dataservice.name }}
  template:
    metadata:
      annotations:
      {{- if .Values.dataservice.deployment.autoRestart }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- with .Values.dataservice.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.dataservice.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "portkey.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.dataservice.name }}
    spec:
      imagePullSecrets: 
      {{- range .Values.imageCredentials }}
      - name: {{ .name }}
      {{- end }}

      securityContext:
        {{- toYaml .Values.dataservice.deployment.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "dataservice.serviceAccountName" . }}
      containers:
        - name: {{ .Values.dataservice.name }}
          {{- with .Values.dataservice.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "portkey.commonEnv" . | nindent 12 }}
            {{- include "logStore.commonEnv" . | nindent 12 }}
            - name: PORT
              value: {{ .Values.dataservice.containerPort | quote }}
            - name: PRIVATE_DEPLOYMENT
              value: "ON"
            - name: SERVICE_NAME
              value: {{ include "portkey.fullname" . }}-{{ .Values.dataservice.name }}
            - name: FINETUNES_BUCKET
              value: {{ .Values.dataservice.finetuneBucket }}
            - name: LOG_EXPORTS_BUCKET
              value: {{ .Values.dataservice.logexportsBucket }}
            {{- with .Values.dataservice.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.commonEnv }}
              {{ toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.images.dataserviceImage.repository }}:{{ .Values.images.dataserviceImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.dataserviceImage.pullPolicy }}
          ports:
            - name: dataservice
              containerPort: {{ .Values.dataservice.containerPort }}
              protocol: TCP
          {{- with .Values.dataservice.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataservice.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataservice.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.dataservice.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.dataservice.deployment.securityContext | nindent 12 }}
          {{- with .Values.dataservice.deployment.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataservice.deployment.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.dataservice.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.dataservice.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataservice.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataservice.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataservice.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}