{{- if .Values.dataservice.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataservice.serviceAccountName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.dataservice.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.dataservice.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}