{{- if and .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.appTLSCerts.certificate.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-5"  # Ensure this runs AFTER the Issuer (-5)
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  secretName: {{ .Release.Name }}-certmanager-webhook-ca
  duration: {{ .Values.appTLSCerts.certificate.duration | quote }}
  renewBefore: {{ .Values.appTLSCerts.certificate.renewBefore | quote }}
  dnsNames:
    - "*.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    name: {{ .Values.appTLSCerts.issuer.name | quote }}
    kind: {{ .Values.appTLSCerts.issuer.kind | quote }}
  usages:
    - digital signature
    - key encipherment
{{- end }}