{{- if .Values.config.aws.acm.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: portkey-app-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "redis_connection_url"
          objectType: "secretsmanager"
        - objectName: "redis_tls_enabled"
          objectType: "secretsmanager"
        - objectName: "redis_mode"
          objectType: "secretsmanager"
        - objectName: "redis_host"
          objectType: "secretsmanager"
        - objectName: "mysql_db"
          objectType: "secretsmanager"
        - objectName: "mysql_host"
          objectType: "secretsmanager"
        - objectName: "mysql_password"
          objectType: "secretsmanager"
        - objectName: "mysql_port"
          objectType: "secretsmanager"
        - objectName: "mysql_user"
          objectType: "secretsmanager"
        - objectName: "mysql_ssl_mode"
          objectType: "secretsmanager"
        - objectName: "mysql_root_password"
          objectType: "secretsmanager"
        - objectName: "mysql_database"
          objectType: "secretsmanager"
        - objectName: "mysql_username"
          objectType: "secretsmanager"
        - objectName: "oauthType"
          objectType: "secretsmanager"
        - objectName: "oauthIssuerUrl"
          objectType: "secretsmanager"
        - objectName: "oauthClientId"
          objectType: "secretsmanager"
        - objectName: "oauthClientSecret"
          objectType: "secretsmanager"
        - objectName: "oauthRedirectURI"
          objectType: "secretsmanager"
        - objectName: "oauthMetadataXml"
          objectType: "secretsmanager"
        - objectName: "jwtPrivateKey"
          objectType: "secretsmanager"
        - objectName: "smtpHost"
          objectType: "secretsmanager"
        - objectName: "smtpPort"
          objectType: "secretsmanager"
        - objectName: "smtpUser"
          objectType: "secretsmanager"
        - objectName: "smtpPassword"
          objectType: "secretsmanager"
        - objectName: "smtpFrom"
          objectType: "secretsmanager"
{{- end }}
