{{- if .Values.config.aws.acm.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: portkey-app-aws-secrets
spec:
  provider: aws
  secretObjects:
  {{- if .Values.config.existingSecretName }}
  - secretName: {{.Values.config.existingSecretName}}
    type: Opaque
    data:
    - objectName: oauthType
      key: oauthType
    - objectName: oauthIssuerUrl
      key: oauthIssuerUrl
    - objectName: oauthClientId
      key: oauthClientId
    - objectName: oauthClientSecret
      key: oauthClientSecret
    - objectName: oauthRedirectURI
      key: oauthRedirectURI
    - objectName: oauthMetadataXml
      key: oauthMetadataXml
    - objectName: jwtPrivateKey
      key: jwtPrivateKey
    - objectName: smtpHost
      key: smtpHost
    - objectName: smtpPort
      key: smtpPort
    - objectName: smtpUser
      key: smtpUser
    - objectName: smtpPassword
      key: smtpPassword
    - objectName: smtpFrom
      key: smtpFrom
  {{- end }}
  {{- if .Values.redis.external.existingSecretName }}
  - secretName: {{.Values.redis.external.existingSecretName}}
    type: Opaque
    data:
    - objectName: redis_connection_url
      key: redis_connection_url
    - objectName: redis_tls_enabled
      key: redis_tls_enabled
    - objectName: redis_mode
      key: redis_mode
    - objectName: redis_host
      key: redis_host
    - objectName: redis_port
      key: redis_port
  {{- end }}
  {{- if .Values.mysql.external.existingSecretName }}
  - secretName: {{.Values.mysql.external.existingSecretName}}
    type: Opaque
    data:
    - objectName: mysql_db
      key: mysql_db
    - objectName: mysql_host
      key: mysql_host
    - objectName: mysql_password
      key: mysql_password
    - objectName: mysql_port
      key: mysql_port
    - objectName: mysql_user
      key: mysql_user
    {{- end }}
  parameters:
    objects: |
        - objectName: "redis_connection_url"
          objectType: "secretsmanager"
        - objectName: "redis_tls_enabled"
          objectType: "secretsmanager"
        - objectName: "redis_mode"
          objectType: "secretsmanager"
        - objectName: "redis_host"
          objectType: "secretsmanager"
        - objectName: "mysql_db"
          objectType: "secretsmanager"
        - objectName: "mysql_host"
          objectType: "secretsmanager"
        - objectName: "mysql_password"
          objectType: "secretsmanager"
        - objectName: "mysql_port"
          objectType: "secretsmanager"
        - objectName: "mysql_user"
          objectType: "secretsmanager"
        - objectName: "mysql_ssl_mode"
          objectType: "secretsmanager"
        - objectName: "mysql_root_password"
          objectType: "secretsmanager"
        - objectName: "oauthType"
          objectType: "secretsmanager"
        - objectName: "oauthIssuerUrl"
          objectType: "secretsmanager"
        - objectName: "oauthClientId"
          objectType: "secretsmanager"
        - objectName: "oauthClientSecret"
          objectType: "secretsmanager"
        - objectName: "oauthRedirectURI"
          objectType: "secretsmanager"
        - objectName: "oauthMetadataXml"
          objectType: "secretsmanager"
        - objectName: "jwtPrivateKey"
          objectType: "secretsmanager"
        - objectName: "smtpHost"
          objectType: "secretsmanager"
        - objectName: "smtpPort"
          objectType: "secretsmanager"
        - objectName: "smtpUser"
          objectType: "secretsmanager"
        - objectName: "smtpPassword"
          objectType: "secretsmanager"
        - objectName: "smtpFrom"
          objectType: "secretsmanager"
{{- end }}
