{{- if .Values.config.aws.secretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: portkey-app-aws-secrets
spec:
  provider: aws
  secretObjects:
  {{- if .Values.config.existingSecretName }}
  - secretName: {{.Values.config.existingSecretName}}
    type: Opaque
    data:
    - objectName: oauthType
      key: oauthType
    - objectName: oauthIssuerUrl
      key: oauthIssuerUrl
    - objectName: oauthClientId
      key: oauthClientId
    - objectName: oauthClientSecret
      key: oauthClientSecret
    - objectName: oauthRedirectURI
      key: oauthRedirectURI
    - objectName: oauthMetadataXml
      key: oauthMetadataXml
    - objectName: jwtPrivateKey
      key: jwtPrivateKey
    - objectName: smtpHost
      key: smtpHost
    - objectName: smtpPort
      key: smtpPort
    - objectName: smtpUser
      key: smtpUser
    - objectName: smtpPassword
      key: smtpPassword
    - objectName: smtpFrom
      key: smtpFrom
  {{- end }}
  {{- if .Values.redis.external.existingSecretName }}
  - secretName: {{.Values.redis.external.existingSecretName}}
    type: Opaque
    data:
    - objectName: redis_connection_url
      key: redis_connection_url
    - objectName: redis_tls_enabled
      key: redis_tls_enabled
    - objectName: redis_mode
      key: redis_mode
    - objectName: redis_store
      key: redis_store
  {{- end }}
  {{- if .Values.mysql.external.existingSecretName }}
  - secretName: {{.Values.mysql.external.existingSecretName}}
    type: Opaque
    data:
    - objectName: mysql_db
      key: mysql_db
    - objectName: mysql_host
      key: mysql_host
    - objectName: mysql_password
      key: mysql_password
    - objectName: mysql_port
      key: mysql_port
    - objectName: mysql_user
      key: mysql_user
    {{- if .Values.mysql.external.ssl.enabled }}
    - objectName: mysql_ssl_mode
      key: mysql_ssl_mode
    {{- end }}
    {{- if not .Values.mysql.external.enabled }}
    - objectName: mysql_root_password
      key: mysql_root_password
    {{- end }}
  {{- end }}
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:517194595696:secret:test/acm-oVYUUj"
        objectType: "secretsmanager"
        jmesPath:
          - path: oauthType
            objectAlias: oauthType
          - path: oauthIssuerUrl
            objectAlias: oauthIssuerUrl
          - path: oauthClientId
            objectAlias: oauthClientId
          - path: oauthClientSecret
            objectAlias: oauthClientSecret
          - path: oauthRedirectURI
            objectAlias: oauthRedirectURI
          - path: oauthMetadataXml
            objectAlias: oauthMetadataXml
          - path: jwtPrivateKey
            objectAlias: jwtPrivateKey
          - path: smtpHost
            objectAlias: smtpHost
          - path: smtpPort
            objectAlias: smtpPort
          - path: smtpUser
            objectAlias: smtpUser
          - path: smtpPassword
            objectAlias: smtpPassword
          - path: smtpFrom
            objectAlias: smtpFrom
          - path: redis_connection_url
            objectAlias: redis_connection_url
          - path: redis_tls_enabled
            objectAlias: redis_tls_enabled
          - path: redis_mode
            objectAlias: redis_mode
          - path: redis_store
            objectAlias: redis_store
          - path: mysql_db
            objectAlias: mysql_db
          - path: mysql_host
            objectAlias: mysql_host
          - path: mysql_password
            objectAlias: mysql_password
          - path: mysql_port
            objectAlias: mysql_port
          - path: mysql_user
            objectAlias: mysql_user
          - path: mysql_ssl_mode
            objectAlias: mysql_ssl_mode
          - path: mysql_root_password
            objectAlias: mysql_root_password
{{- end }}
