{{- if .Values.dataservice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portkeyenterprise.fullname" . }}-{{ .Values.dataservice.name }}
  labels:
    {{- include "dataservice.labels" . | nindent 4 }}
    {{- with .Values.dataservice.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.dataservice.deployment.autoRestart }}
      rollme: {{ randAlphaNum 5 | quote }}
    {{- end }}
    {{- include "portkeyenterprise.annotations" . | nindent 6 }}
    {{- with .Values.dataservice.deployment.annotations }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  {{- if not .Values.dataservice.autoscaling.enabled }}
  replicas: {{ .Values.dataservice.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dataservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.dataservice.deployment.autoRestart }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- with .Values.dataservice.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dataservice.labels" . | nindent 8 }}
        {{- with .Values.dataservice.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets: 
      {{- range .Values.imageCredentials }}
      - name: {{ .name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.dataservice.deployment.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "dataservice.serviceAccountName" . }}
      containers:
        - name: {{ .Values.dataservice.name }}
          {{- with .Values.dataservice.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: GATEWAY_BASE_URL
              value: http://{{ include "portkeyenterprise.fullname" . }}:{{ .Values.service.port }}
            {{- include "dataservice.commonEnv" . | nindent 12 }}
            {{- include "controlPlane.commonEnv" . | nindent 12 }}
            {{- include "cacheStore.commonEnv" . | nindent 12 }}
            {{- include "logStore.commonEnv" . | nindent 12 }}
          image: "{{ .Values.images.dataserviceImage.repository }}:{{ .Values.images.dataserviceImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.dataserviceImage.pullPolicy }}
          ports:
            - name: dataservice
              containerPort: {{ .Values.dataservice.containerPort }}
              protocol: TCP
          {{- with .Values.dataservice.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataservice.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataservice.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.dataservice.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.dataservice.deployment.securityContext | nindent 12 }}
          {{- with .Values.dataservice.deployment.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dataservice.deployment.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.dataservice.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.dataservice.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataservice.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataservice.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataservice.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}