{{- if and .Values.dataservice.enabled .Values.dataservice.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataservice.serviceAccountName" . }}
  labels:
    {{- include "dataservice.labels" . | nindent 4 }}
    {{- with .Values.dataservice.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkeyenterprise.annotations" . | nindent 4 }}
    {{- with .Values.dataservice.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}