apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portkeyenterprise.fullname" . }}
  labels:
    {{- include "gateway.labels" . }}
    {{- with .Values.service.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- if .Values.autoRestart }}
    rollme: {{ randAlphaNum 5 | quote }}
  {{- end }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portkeyenterprise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.autoRestart }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.useVaultInjection }}
        {{- include "portkeyenterprise.vaultAnnotations" . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gateway.labels" . | nindent 4 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets: 
      {{- range .Values.imageCredentials }}
      - name: {{ .name }}
      {{- end }}
      serviceAccountName: {{ include "portkeyenterprise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.gatewayImage.repository }}:{{ .Values.images.gatewayImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.gatewayImage.pullPolicy }}
          ports:
            - name: "gateway"
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if .Values.dataservice.enabled }}
              - name: DATASERVICE_BASEPATH
                value: http://{{ include "portkeyenterprise.fullname" . }}-{{ .Values.dataservice.name }}:{{ .Values.dataservice.service.port }}
            {{- end }}
            {{- include "portkeyenterprise.commonEnv" . | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}