{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portkeyenterprise.serviceAccountName" . }}
  labels:
    {{- include "gateway.labels" . }}
  annotations:
    {{- include "portkeyenterprise.annotations" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
