apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.gatewaySecretsName" .}}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
type: Opaque
data:
  logStoreAccessKey: {{ .Values.logStorage.s3.AWS_ACCESS_KEY_ID | b64enc }}
  logStoreSecretKey: {{ .Values.logStorage.s3.AWS_SECRET_ACCESS_KEY | b64enc }}
  awsAssumeRoleAccessKeyId: {{ .Values.logStorage.s3_assume.AWS_ASSUME_ROLE_ACCESS_KEY_ID | b64enc }}
  awsAssumeRoleSecretAccessKey: {{ .Values.logStorage.s3_assume.AWS_ASSUME_ROLE_SECRET_ACCESS_KEY | b64enc }}
  azureStorageKey: {{ .Values.logStorage.azure.AZURE_STORAGE_ACCOUNT | b64enc }}
  portkeyClientAuth: {{ .Values.logStorage.clientAuth | b64enc }}