apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.gatewaySecretsName" .}}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.logStorage.s3_compat.enabled}}
  logStore: {{ .Values.logStorage.s3_compat.type | b64enc | quote }}
  logStoreAccessKey: {{ .Values.logStorage.s3_compat.LOG_STORE_ACCESS_KEY | b64enc | quote }}
  logStoreSecretKey: {{ .Values.logStorage.s3_compat.LOG_STORE_SECRET_KEY | b64enc | quote }}
  logStoreRegion: {{ .Values.logStorage.s3_compat.LOG_STORE_REGION | b64enc | quote }}
  logStoreGenerationsBucket: {{ .Values.logStorage.s3_compat.LOG_STORE_GENERATIONS_BUCKET | b64enc | quote }}
  logStoreBasePath: {{ .Values.logStorage.s3_compat.LOG_STORE_BASEPATH | b64enc | quote }}
  {{- end }}
  {{- if .Values.logStorage.mongo.enabled}}
  logStore: {{ "mongo" | b64enc }}
  mongoConnectionUrl: {{ .Values.logStorage.mongo.MONGO_DB_CONNECTION_URL | b64enc | quote }}
  mongoDatabase: {{ .Values.logStorage.mongo.MONGO_DATABASE | b64enc | quote }}
  mongoGenerationsCollection: {{ .Values.logStorage.mongo.MONGO_COLLECTION_NAME | b64enc | quote }}
  mongoHooksCollection: {{ .Values.logStorage.MONGO_GENERATION_HOOKS_COLLECTION_NAME.LOG_STORE_GENERATIONS_BUCKET | b64enc | quote }}
  {{- end }}
  {{- if .Values.logStorage.s3_assume.enabled}}
  logStore: {{ "s3_assume" | b64enc | quote }}
  logStoreAccessKey: {{ .Values.logStorage.s3_assume.LOG_STORE_ACCESS_KEY | b64enc | quote }}
  logStoreSecretKey: {{ .Values.logStorage.s3_assume.LOG_STORE_SECRET_KEY | b64enc | quote }}
  logStoreRegion: {{ .Values.logStorage.s3_assume.LOG_STORE_REGION | b64enc | quote }}
  logStoreGenerationsBucket: {{ .Values.logStorage.s3_assume.LOG_STORE_GENERATIONS_BUCKET | b64enc | quote }}
  logStoreAwsRoleArn: {{ .Values.logStorage.s3_assume.LOG_STORE_AWS_ROLE_ARN | b64enc | quote }}
  logStoreExternalId: {{ .Values.logStorage.s3_assume.LOG_STORE_AWS_EXTERNAL_ID | b64enc | quote }}
  {{- end }}
  {{- if .Values.logStorage.azure.enabled}}
  logStore: {{ "azure" | b64enc }}
  azureStorageAccount: {{ .Values.logStorage.azure.AZURE_STORAGE_ACCOUNT | b64enc | quote }}
  azureStorageKey: {{ .Values.logStorage.azure.AZURE_STORAGE_KEY | b64enc | quote }}
  azureStorageContainer: {{ .Values.logStorage.azure.AZURE_STORAGE_CONTAINER | b64enc | quote }}
  {{- end }}
  {{- if .Values.bedrockAssumed.enabled}}
  bedrockAssumedAccessKey: {{ .Values.bedrockAssumed.AWS_ASSUME_ROLE_ACCESS_KEY_ID | b64enc | quote }}
  bedrockAssumedSecretKey: {{ .Values.bedrockAssumed.AWS_ASSUME_ROLE_SECRET_ACCESS_KEY | b64enc | quote }}
  bedrockAssumedRegion: {{ .Values.bedrockAssumed.AWS_ASSUME_ROLE_REGION | b64enc | quote }}
  {{- end }}