{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.gateway.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.gateway.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.gateway.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  ports:
    - name: gateway
      port: {{ .Values.gateway.service.port }}
      targetPort: gateway
      protocol: TCP
  selector:
    {{- include "portkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.gateway.name }}
  {{- end}}