imageCredentials:
  - name: portkeyenterpriseregistrycredentials
    create: true
    registry: https://index.docker.io/v1/
    username: <docker-username>
    password: <docker-password>
imagePullSecrets: [portkeyenterpriseregistrycredentials]

config:
  jwtPrivateKey: "some_random_string"
  noAuth:
    enabled: true

logStorage:
  logStore: "s3"
  s3Compat:
    enabled: true
    LOG_STORE_ACCESS_KEY: <s3-access-key>
    LOG_STORE_SECRET_KEY: <s3-secret-key>
    LOG_STORE_REGION: <s3-region>
    LOG_STORE_GENERATIONS_BUCKET: "generations-raw"

mysql:
  external:
    enabled: false
    user: "portkey"
    password: "portkey@123"
    database: "portkey"
    rootPassword: "portkey@123"

redis:
  external:
    enabled: false
    tlsEnabled: "false"
    mode: "standalone"
    store: "redis"

clickhouse:
  external:
    enabled: false
    user: "default"
    password: "portkey@123"