apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 404 /index.html;

        # Additional security headers
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
    }
  .env: |
    VITE_API_URL={{ .Values.config.defaultGatewayURL | quote }}
    VITE_BASE_URL="http://{{ include "portkey.fullname" . }}-{{ .Values.backend.name }}:{{ .Values.backend.containerPort }}"
    VITE_PRIVATE_DEPLOYMENT="ON"
    {{- if .Values.config.oauth.enabled }}
    VITE_AUTH_MODE="SSO"
    {{- end }}
    {{- if .Values.config.noAuth.enabled }}
    VITE_AUTH_MODE="NO_AUTH"
    {{- end }}