{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.secretsName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
data:
  {{- if .Values.config.noAuth.enabled }}
    jwtSecret: {{ .Values.config.noAuth.jwtSecret | b64enc | quote }}
  {{- else if .Values.config.oauth.enabled }}
    oauthClientId: {{ .Values.config.oauth.oauthClientId | b64enc | quote }}
    oauthIssuerUrl: {{ .Values.config.oauth.oauthIssuerUrl | b64enc | quote }}
  {{- end }}
{{- end }}