apiVersion: v2
name: gateway
description: Helm chart to deploy the Portkey AI Gateway application in a hybrid cloud environment.
home: https://portkey.ai/
icon: https://avatars.githubusercontent.com/u/131141116?s=200&v=4
type: application
version: "1.1.3"
appVersion: "1.12.2"
maintainers:
  - name: Ayush
    email: ayush@portkey.ai
    url: https://github.com/ayush-portkey
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/Portkey-AI/helm
