{{- if include "clickhouse.replicationEnabled" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.headlessServiceName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.clickhouse.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.clickhouse.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: ch
      port: {{ .Values.clickhouse.service.httpPort }}
      targetPort: ch
      protocol: TCP
    - name: ch-native
      port: {{ .Values.clickhouse.service.nativePort }}
      targetPort: ch-native
      protocol: TCP
    - name: ch-interserver
      port: {{ .Values.clickhouse.containerInterserverPort }}
      targetPort: ch-interserver
      protocol: TCP
  selector:
    {{- include "portkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.clickhouse.name }}
{{- end }}
