{{- if not .Values.clickhouse.external.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portkey.clickhouseSecretsName" .}}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
data:
  {{- if .Values.clickhouse.external.enabled }}
  clickhouse_user: {{ .Values.clickhouse.external.user | b64enc }}
  clickhouse_password: {{ .Values.clickhouse.external.password | b64enc }}
  clickhouse_host: {{ .Values.clickhouse.external.host | b64enc }}
  clickhouse_port: {{ .Values.clickhouse.external.port | b64enc }}
  clickhouse_native_port: {{ .Values.clickhouse.external.nativePort | b64enc }}
  clickhouse_db: {{ .Values.clickhouse.external.database | b64enc }}
  clickhouse_tls: {{ .Values.clickhouse.external.tls | toString | b64enc }}
  {{- else }}
  clickhouse_user: {{ .Values.clickhouse.external.user | b64enc }}
  clickhouse_password: {{ .Values.clickhouse.external.password | b64enc }}
  clickhouse_host: {{ printf "%s-%s" (include "portkey.fullname" .) .Values.clickhouse.name | b64enc }}
  clickhouse_port: {{ toString .Values.clickhouse.containerHttpPort | b64enc }}
  clickhouse_native_port: {{ toString .Values.clickhouse.containerNativePort | b64enc }}
  clickhouse_db: {{ .Values.clickhouse.external.database | b64enc }}
  clickhouse_tls: {{ .Values.clickhouse.external.tls | toString | b64enc }}
  {{- end}}
{{- end }}