{{- if not .Values.clickhouse.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portkey.fullname" . }}-{{ .Values.clickhouse.name }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.clickhouse.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.clickhouse.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.clickhouse.service.type }}
  {{- with .Values.clickhouse.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  loadBalancerIP: {{ .Values.clickhouse.service.loadBalancerIP }}
  ports:
    - name: ch
      port: {{ .Values.clickhouse.service.httpPort }}
      targetPort: ch
      protocol: TCP
    - name: ch-native
      port: {{ .Values.clickhouse.service.nativePort }}
      targetPort: ch-native
      protocol: TCP
  selector:
    {{- include "portkey.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "portkey.fullname" . }}-{{ .Values.clickhouse.name }}
{{- end }}