{{- if and (not .Values.clickhouse.external.enabled) .Values.clickhouse.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickhouse.serviceAccountName" . }}
  labels:
    {{- include "portkey.labels" . | nindent 4 }}
    {{- with .Values.clickhouse.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "portkey.annotations" . | nindent 4 }}
    {{- with .Values.clickhouse.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}